# Makefile for Array Data Type Example


## Build Configurations ##

# Compilier
CXX:=g++

# Compilier Flags
CXXFLAGS:=-Wall -g -std=c++17

# Source File Directory
SOURCE_DIR:=src/

# Build Output Directory
BUILD_DIR:= build/

########################################

# Default Target
all: 